#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cap
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="Capping")]
	public partial class DataClasses1DataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region 可扩展性方法定义
    partial void OnCreated();
    partial void InserttbDrugConfig(tbDrugConfig instance);
    partial void UpdatetbDrugConfig(tbDrugConfig instance);
    partial void DeletetbDrugConfig(tbDrugConfig instance);
    partial void InserttbOpUser(tbOpUser instance);
    partial void UpdatetbOpUser(tbOpUser instance);
    partial void DeletetbOpUser(tbOpUser instance);
    #endregion
		
		public DataClasses1DataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<tbDrugConfig> tbDrugConfig
		{
			get
			{
				return this.GetTable<tbDrugConfig>();
			}
		}
		
		public System.Data.Linq.Table<tbTestDrug> tbTestDrug
		{
			get
			{
				return this.GetTable<tbTestDrug>();
			}
		}
		
		public System.Data.Linq.Table<tbOpUser> tbOpUser
		{
			get
			{
				return this.GetTable<tbOpUser>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbDrugConfig")]
	public partial class tbDrugConfig : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private string _DrugName;
		
		private string _DrugUnit;
		
		private System.Nullable<int> _ProductNo;
		
		private string _diameter;
		
		private string _height;
		
		private System.Nullable<System.DateTime> _InsertDate;
		
		private string _ImagePath;
		
		private string _DrugCode;
		
		private System.Nullable<int> _PLC_Weight;
		
		private System.Nullable<int> _PLC_Height;
		
		private string _Delay;
		
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnDrugNameChanging(string value);
    partial void OnDrugNameChanged();
    partial void OnDrugUnitChanging(string value);
    partial void OnDrugUnitChanged();
    partial void OnProductNoChanging(System.Nullable<int> value);
    partial void OnProductNoChanged();
    partial void OndiameterChanging(string value);
    partial void OndiameterChanged();
    partial void OnheightChanging(string value);
    partial void OnheightChanged();
    partial void OnInsertDateChanging(System.Nullable<System.DateTime> value);
    partial void OnInsertDateChanged();
    partial void OnImagePathChanging(string value);
    partial void OnImagePathChanged();
    partial void OnDrugCodeChanging(string value);
    partial void OnDrugCodeChanged();
    partial void OnPLC_WeightChanging(System.Nullable<int> value);
    partial void OnPLC_WeightChanged();
    partial void OnPLC_HeightChanging(System.Nullable<int> value);
    partial void OnPLC_HeightChanged();
    partial void OnDelayChanging(string value);
    partial void OnDelayChanged();
    #endregion
		
		public tbDrugConfig()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DrugName", DbType="VarChar(255)")]
		public string DrugName
		{
			get
			{
				return this._DrugName;
			}
			set
			{
				if ((this._DrugName != value))
				{
					this.OnDrugNameChanging(value);
					this.SendPropertyChanging();
					this._DrugName = value;
					this.SendPropertyChanged("DrugName");
					this.OnDrugNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DrugUnit", DbType="VarChar(255)")]
		public string DrugUnit
		{
			get
			{
				return this._DrugUnit;
			}
			set
			{
				if ((this._DrugUnit != value))
				{
					this.OnDrugUnitChanging(value);
					this.SendPropertyChanging();
					this._DrugUnit = value;
					this.SendPropertyChanged("DrugUnit");
					this.OnDrugUnitChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ProductNo", DbType="Int")]
		public System.Nullable<int> ProductNo
		{
			get
			{
				return this._ProductNo;
			}
			set
			{
				if ((this._ProductNo != value))
				{
					this.OnProductNoChanging(value);
					this.SendPropertyChanging();
					this._ProductNo = value;
					this.SendPropertyChanged("ProductNo");
					this.OnProductNoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_diameter", DbType="VarChar(20)")]
		public string diameter
		{
			get
			{
				return this._diameter;
			}
			set
			{
				if ((this._diameter != value))
				{
					this.OndiameterChanging(value);
					this.SendPropertyChanging();
					this._diameter = value;
					this.SendPropertyChanged("diameter");
					this.OndiameterChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_height", DbType="VarChar(20)")]
		public string height
		{
			get
			{
				return this._height;
			}
			set
			{
				if ((this._height != value))
				{
					this.OnheightChanging(value);
					this.SendPropertyChanging();
					this._height = value;
					this.SendPropertyChanged("height");
					this.OnheightChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_InsertDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> InsertDate
		{
			get
			{
				return this._InsertDate;
			}
			set
			{
				if ((this._InsertDate != value))
				{
					this.OnInsertDateChanging(value);
					this.SendPropertyChanging();
					this._InsertDate = value;
					this.SendPropertyChanged("InsertDate");
					this.OnInsertDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ImagePath", DbType="VarChar(255)")]
		public string ImagePath
		{
			get
			{
				return this._ImagePath;
			}
			set
			{
				if ((this._ImagePath != value))
				{
					this.OnImagePathChanging(value);
					this.SendPropertyChanging();
					this._ImagePath = value;
					this.SendPropertyChanged("ImagePath");
					this.OnImagePathChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DrugCode", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		public string DrugCode
		{
			get
			{
				return this._DrugCode;
			}
			set
			{
				if ((this._DrugCode != value))
				{
					this.OnDrugCodeChanging(value);
					this.SendPropertyChanging();
					this._DrugCode = value;
					this.SendPropertyChanged("DrugCode");
					this.OnDrugCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PLC_Weight", UpdateCheck=UpdateCheck.Never)]
		public System.Nullable<int> PLC_Weight
		{
			get
			{
				return this._PLC_Weight;
			}
			set
			{
				if ((this._PLC_Weight != value))
				{
					this.OnPLC_WeightChanging(value);
					this.SendPropertyChanging();
					this._PLC_Weight = value;
					this.SendPropertyChanged("PLC_Weight");
					this.OnPLC_WeightChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PLC_Height", UpdateCheck=UpdateCheck.Never)]
		public System.Nullable<int> PLC_Height
		{
			get
			{
				return this._PLC_Height;
			}
			set
			{
				if ((this._PLC_Height != value))
				{
					this.OnPLC_HeightChanging(value);
					this.SendPropertyChanging();
					this._PLC_Height = value;
					this.SendPropertyChanged("PLC_Height");
					this.OnPLC_HeightChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Delay", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		public string Delay
		{
			get
			{
				return this._Delay;
			}
			set
			{
				if ((this._Delay != value))
				{
					this.OnDelayChanging(value);
					this.SendPropertyChanging();
					this._Delay = value;
					this.SendPropertyChanged("Delay");
					this.OnDelayChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbTestDrug")]
	public partial class tbTestDrug
	{
		
		private string _DrugName;
		
		private string _DrugCode;
		
		public tbTestDrug()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DrugName", DbType="VarChar(255)")]
		public string DrugName
		{
			get
			{
				return this._DrugName;
			}
			set
			{
				if ((this._DrugName != value))
				{
					this._DrugName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DrugCode", CanBeNull=false)]
		public string DrugCode
		{
			get
			{
				return this._DrugCode;
			}
			set
			{
				if ((this._DrugCode != value))
				{
					this._DrugCode = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbOpUser")]
	public partial class tbOpUser : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private string _Password;
		
		private int _OpType;
		
		private string _UserCode;
		
		private string _UserName;
		
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnPasswordChanging(string value);
    partial void OnPasswordChanged();
    partial void OnOpTypeChanging(int value);
    partial void OnOpTypeChanged();
    partial void OnUserCodeChanging(string value);
    partial void OnUserCodeChanged();
    partial void OnUserNameChanging(string value);
    partial void OnUserNameChanged();
    #endregion
		
		public tbOpUser()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Password", DbType="VarChar(255)")]
		public string Password
		{
			get
			{
				return this._Password;
			}
			set
			{
				if ((this._Password != value))
				{
					this.OnPasswordChanging(value);
					this.SendPropertyChanging();
					this._Password = value;
					this.SendPropertyChanged("Password");
					this.OnPasswordChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OpType", DbType="Int")]
		public int OpType
		{
			get
			{
				return this._OpType;
			}
			set
			{
				if ((this._OpType != value))
				{
					this.OnOpTypeChanging(value);
					this.SendPropertyChanging();
					this._OpType = value;
					this.SendPropertyChanged("OpType");
					this.OnOpTypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserCode", DbType="VarChar(255) NOT NULL", CanBeNull=false)]
		public string UserCode
		{
			get
			{
				return this._UserCode;
			}
			set
			{
				if ((this._UserCode != value))
				{
					this.OnUserCodeChanging(value);
					this.SendPropertyChanging();
					this._UserCode = value;
					this.SendPropertyChanged("UserCode");
					this.OnUserCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserName", DbType="VarChar(255)")]
		public string UserName
		{
			get
			{
				return this._UserName;
			}
			set
			{
				if ((this._UserName != value))
				{
					this.OnUserNameChanging(value);
					this.SendPropertyChanging();
					this._UserName = value;
					this.SendPropertyChanged("UserName");
					this.OnUserNameChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
